/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-primary": "var(--color-on-primary, #ffffff)",
        "on-secondary-fixed": "#1c1b1b",
        "on-error": "#ffffff",
        "inverse-primary": "#c6c6c6",
        "on-primary-fixed": "#1b1b1b",
        "on-tertiary": "#ffffff",
        "surface-container": "var(--color-surface-container, #efeded)",
        "on-surface-variant": "var(--color-on-surface-variant, #4c4546)",
        "secondary-fixed-dim": "#c8c6c5",
        "primary-fixed-dim": "#c6c6c6",
        "tertiary-fixed-dim": "#c6c6c6",
        "surface-container-highest": "var(--color-surface-container-highest, #e4e2e2)",
        "on-error-container": "#93000a",
        "error-container": "#ffdad6",
        "inverse-surface": "#303031",
        "outline": "var(--color-outline, #7e7576)",
        "tertiary-container": "#1b1b1b",
        "primary-fixed": "#e2e2e2",
        "on-primary-fixed-variant": "#474747",
        "surface": "var(--color-surface, #fbf9f8)",
        "on-secondary-fixed-variant": "#474646",
        "on-tertiary-fixed-variant": "#474747",
        "secondary": "var(--color-secondary, #5f5e5e)",
        "on-tertiary-container": "#848484",
        "on-background": "var(--color-on-surface, #1b1c1c)",
        "primary-container": "#1b1b1b",
        "on-surface": "var(--color-on-surface, #1b1c1c)",
        "background": "var(--color-surface, #fbf9f8)",
        "on-secondary-container": "#656464",
        "tertiary-fixed": "#e2e2e2",
        "surface-container-high": "var(--color-surface-container-high, #e9e8e7)",
        "primary": "var(--color-primary, #000000)",
        "surface-tint": "#5e5e5e",
        "surface-bright": "var(--color-surface-bright, #fbf9f8)",
        "surface-container-low": "var(--color-surface-container-low, #f5f3f3)",
        "outline-variant": "var(--color-outline-variant, #cfc4c5)",
        "secondary-fixed": "#e5e2e1",
        "on-tertiary-fixed": "#1b1b1b",
        "surface-dim": "var(--color-surface-dim, #dbdad9)",
        "on-primary-container": "#848484",
        "on-secondary": "#ffffff",
        "error": "#ba1a1a",
        "surface-variant": "var(--color-surface-variant, #e4e2e2)",
        "surface-container-lowest": "var(--color-surface-container-lowest, #ffffff)",
        "tertiary": "var(--color-primary, #000000)",
        "secondary-container": "#e5e2e1",
        "inverse-on-surface": "#f2f0f0",
      },
      borderRadius: {
        none: "0px",
        sm: "0px",
        DEFAULT: "0px",
        md: "0px",
        lg: "0px",
        xl: "0px",
        "2xl": "0px",
        "3xl": "0px",
        full: "9999px",
      },
      spacing: {
        "space-xxs": "0.25rem",
        "space-xs": "0.5rem",
        "space-sm": "0.75rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2rem",
        "space-2xl": "3rem",
        "space-3xl": "4.5rem",
        "space-4xl": "6rem",
        gutter: "1.5rem",
        "margin-mobile": "1.25rem",
        "margin-desktop": "3rem",
      },
      fontFamily: {
        "label-meta": ["Inter", "sans-serif"],
        "label-code": ["'JetBrains Mono'", "monospace"],
        "display-xl": ["Inter", "sans-serif"],
        "title-sm": ["Inter", "sans-serif"],
        "display-xl-mobile": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Inter", "sans-serif"],
      },
      fontSize: {
        "label-meta": ["11px", { lineHeight: "14px", letterSpacing: "0.08em", fontWeight: "600" }],
        "label-code": ["13px", { lineHeight: "18px", letterSpacing: "-0.01em", fontWeight: "500" }],
        "display-xl": ["80px", { lineHeight: "84px", letterSpacing: "-0.04em", fontWeight: "700" }],
        "title-sm": ["18px", { lineHeight: "24px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "display-xl-mobile": ["44px", { lineHeight: "48px", letterSpacing: "-0.03em", fontWeight: "700" }],
        "headline-lg": ["48px", { lineHeight: "52px", letterSpacing: "-0.03em", fontWeight: "600" }],
        "headline-md": ["28px", { lineHeight: "34px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-md": ["15px", { lineHeight: "24px", letterSpacing: "0em", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "28px", letterSpacing: "-0.01em", fontWeight: "400" }],
        "headline-lg-mobile": ["32px", { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
}
